apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 390149884649.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mini-db.cluster-cw3yacoksmag.us-east-1.rds.amazonaws.com
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: mini-db
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: Xy7!gLz#29RmTqW&

